config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :restaurants do
    resources :comments do
      put 'upvote', to: 'comments#upvote'
    end
  end
  root 'restaurants#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  before_save :defaults
  belongs_to :restaurant
  validates :restaurant, presence: true
  has_ancestry

  def defaults
    self.rank ||= 0
  end

  def self.upvote(id)
    comment = find(id)
    comment.update_attributes(rank: comment.rank.to_i + 1)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :comments
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @comments = Comment.where(restaurant_id: params[:restaurant_id])
  end

  def create
     @comment = Comment.create(comment_params.merge(restaurant_id: params[:restaurant_id]))
  end

  def upvote
    Comment.upvote(params[:comment_id])
    @comment = Comment.find(params[:comment_id])
    render :create
  end

  def comment_params
    params.required(:comment).permit(:body, :author, :parent_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def new
    @restaurant = Restaurant.new
  end

  def create

    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      respond_to do |format|
        format.html {render :show}
        format.json { render @restaurant}
      end
    else
      render 'new'
    end
  end

  def index
    @restaurants = Restaurant.all

    respond_to do |format|
      format.html # show.html.erb
      format.json
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @comments = @restaurant.comments
    respond_to do |format|
      format.html # show.html.erb
      format.json { render @restaurant}
    end
  end


  def restaurant_params
    params.required(:restaurant).permit(:name, :address, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/react_helper.rb
module ReactHelper
  def client(component, id, props)
    sc = script(component, id, props)
    "<div id='#{id}'></div>#{sc}".html_safe
  end

  def isomorphic(component, id, props)
    sc = script(component, id, props)
    resp = HTTParty.post 'http://localhost:3001', body: {component: component, props: props}.to_json,
      headers: {'Content-Type' => 'application/json'}
    "<div id='#{id}'>#{resp}</div>#{sc}".html_safe
  end

  private

  def script(component, id, props)
    "<script>
    //renderReact is from App.js
      document.addEventListener('DOMContentLoaded', function(ev){
        renderReact('#{id}', '#{component}', #{props.to_json});
      });
    </script>"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <nav class="top-bar" data-topbar role="navigation" data-options="sticky_on: large">
  <section class="top-bar-section">
    <ul class="menu">
      <li class="menu-text"><a href="/">Restaurants</a></li>
      <li><%= link_to 'manage restaurants', '/admin' %></li>
      <li><%= link_to 'new restaurant', '/restaurants/new' %></li>
    </ul>
    </section>
  </nav>
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div class="row small-up-1 medium-up-2 large-up-3">
  <% @restaurants.each do |restaurant| %>

  <div class="column">
  <div class="callout">
  <p>
    <%= link_to restaurant, restaurant_path(restaurant) %>
  </p>
  <p>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{restaurant.latitude}%2C#{restaurant.longitude}" %>
  </p>
  <p class="lead">
    <%= restaurant.description %>
  </p>
  <p class="subheader">Comments: <%= restaurant.comments.count %></p>
  </div>
  </div>

  <% end %>
  </div>

app/views/restaurants/new.html.erb
<%= form_for(@restaurant) do |f| %>
<div class="row">
    <div class="large-4 columns">
      <%= f.label :name %>
      <%= f.text_field :name, autocomplete: "off", class: "form-control"  %>
    </div>

    <div class="large-4 columns">
      <%= f.label :address %>
      <%= f.text_field :address, autocomplete: "off" %>
    </div>

    <div class="large-4 columns">
      <%= f.label :description %>
      <%= f.text_field :description, autocomplete: "off", class: "form-control"  %>
    </div>



    <div class="actions">
      <%= f.submit "Save", class: "button primary"  %>
    </div>
</div>
    <% end %>

app/views/restaurants/show.html.erb
<div class="row">
  <h1><%= @restaurant.name %></h1>
</div>
<div class="row">
  <div class="columns medium-6">
    <p>
      <%= @restaurant.description %>
    </p>
    <p>
    <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>
  </p>

  <h3>Nearby locations</h3>
  <ul>
  <% for location in @restaurant.nearbys(10) %>
    <li><%= link_to location.name, location %> (<%= location.distance.round(2) %> km)</li>
  <% end %>
  </ul>
  </div>
  <div class="columns medium-6">
    <h3>Comments</h3>
    <% props = JSON.parse("{\"restaurantId\": #{@restaurant.id}, \"comments\": #{raw(render(template: 'comments/index.json.jbuilder'))}}") %>
    <% if params[:client].present? %>
      <%= #client from react_helper.rb
        client('CommentSection', 'cs', props)
      %>
    <% else %>
      <%= #isomorphic from react_helper.rb
        isomorphic('CommentSection', 'cs', props)
      %>
    <% end %>


  </div>

</div>